### List All Messages
GET http://localhost:3000/messages
Accept: application/json

### Create a New Message
POST http://localhost:3000/messages
Content-Type: application/json

{
  "content": "Hello, this is a new message"
}

### Get a Specific Message
GET http://localhost:3000/messages/1
Accept: application/json
